### ISSUE TITLE
Style demo error when approving new revision

### ISSUE THREAD

**Issue by vinny** [phpbb/customisation-db#381]
When approving a new revision and checking the Install demo option, the revision is approved with the error:
`Failed to remove file "../styles/demo/3.3/board/styles/prosilver_18283/style.cfg": unlink(../styles/demo/3.3/board/styles/prosilver_18283/style.cfg): Permission denied`

The same error occurs when managing the style:
![Captura de tela 2023-10-22 120201](https://github.com/phpbb/customisation-db/assets/474938/c3f8f86a-74fa-4d53-94e3-03cbb7f47f0a)

**Comment by marc1706** [comment]
Most likely was a website issue and unrelated to the cutomisation-db itself. Should be solved now.
